#!/bin/sh

set -euo pipefail

# oracle clienctインストール
# TODO : libaioはどうやって導入すればいい？
# yum -y install libaio
mkdir /tmp/oracle
unzip instantclient-basic-linux.x64-18.3.0.0.0dbru.zip -d /tmp/oracle
unzip instantclient-sqlplus-linux.x64-18.3.0.0.0dbru.zip -d /tmp/oracle
ln -s /tmp/oracle/instantclient_18_3 /tmp/oracle/instantclient
ln -s /tmp/oracle/instantclient/libclntsh.so.18.3 /tmp/oracle/libclntsh.so
export LD_LIBRARY_PATH=/tmp/oracle/instantclient
export ORACLE_HOME=/tmp/oracle/instantclient
export PATH=$PATH:$ORACLE_HOME
sqlplus --help


# Initialization - load function handler
source $LAMBDA_TASK_ROOT/"$(echo $_HANDLER | cut -d. -f1).sh"

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event. The HTTP request will block until one is received
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

  # Extract request ID by scraping response headers received above
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Execute the handler function from the script
  RESPONSE=$($(echo "$_HANDLER" | cut -d. -f2) "$EVENT_DATA")

  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE"
done